### PR TITLE
fixes powerschool showing icons next to every assignment

### LINKED ISSUE #275: some classes are showing missing/exempt logo next to every assignment
latest version

some classes are showing missing/exempt logo next to every assignment. doesn't happen for all classes.

### PR DESCRIPTION
**Pull request by Suhas-13**
accounts for recent PowerSchool change where some courses have the missing icon in the HTML hidden.

fixes #275 

Signed-off-by: Suhas Hariharan <hariharan774531@sas.edu.sg>

### CODE REVIEW

**Comment by Suhas-13** [comment]
@ARtheboss this should fix the issue, can you test as well?

**Comment by Suhas-13** [comment]
#closes 275

**Comment by Suhas-13** [comment]
closes #275

**Comment by Suhas-13** [comment]
fixes #275

File: src/js/helpers.js [hunk 1]
```diff
@@ -187,7 +187,7 @@ function extractAssignmentList () {
     const assignments = [];
     [...table.querySelectorAll('tr')].slice(1, -1).forEach((e, i) => {
         const curr = e.querySelectorAll('td');
-        assignments.push(new ClassAssignment(i, curr[0].innerHTML, curr[1].innerHTML, curr[2].innerHTML, curr[3].hasChildNodes(), curr[4].hasChildNodes(), curr[5].hasChildNodes(), curr[6].hasChildNodes(), curr[7].hasChildNodes(), curr[8].innerHTML, curr[10].innerHTML));
+        assignments.push(new ClassAssignment(i, curr[0].innerHTML, curr[1].innerHTML, curr[2].innerHTML, curr[3].hasChildNodes() && curr[3].childNodes[0].style.display !== 'none', curr[4].hasChildNodes() && curr[4].childNodes[0].style.display !== 'none', curr[5].hasChildNodes() && curr[5].childNodes[0].style.display !== 'none', curr[6].hasChildNodes() && curr[6].childNodes[0].style.display !== 'none', curr[7].hasChildNodes() && curr[7].childNodes[0].style.display !== 'none', curr[8].innerHTML, curr[10].innerHTML));
```
Comment (gary-kim) [inline src/js/helpers.js:190]: You want to turn this into a function instead? Something like this:
```javascript
function (input) {
	return input.hasChildNodes() && input.childNodes[0].style.display !== 'none'.
}
```

File: src/js/helpers.js [hunk 2]
```diff
@@ -203,7 +203,8 @@ function assignments (node) {
     [...node.querySelector('table[align=center').querySelectorAll('tr')].slice(1, -1).forEach((e, i) => {
         const curr = e.querySelectorAll('td');
         const assignment = new Assignment(curr[2]?.innerText || "", curr[curr.length - 1]?.innerText || "", i);
-        if (e.querySelector('img[src="/images/icon_missing.gif"]')) {
+        const missingIcon = e.querySelector('img[src="/images/icon_missing.gif"]');
+        if (missingIcon && missingIcon.style.display !== 'none') {
```
Comment (gary-kim) [inline src/js/helpers.js:207]: You can simply this to the following, actually:
```suggestion
        if (missingIcon?.style.display !== 'none') {
```

**Review by gary-kim — COMMENTED** [review]
Just a few things that could be changed.

File: src/js/helpers.js (hunk 1 above)
Comment (Suhas-13) [reply src/js/helpers.js:190]: thanks for the suggestion. was just trying to get it fixed quickly, but yeah that's definitely a better way of doing it.

**Review by gary-kim — APPROVED** [review]

File: src/js/helpers.js (hunk 1 above)
Comment (gary-kim) [reply src/js/helpers.js:190]: Your call

File: src/js/helpers.js (hunk 2 above)
Comment (Suhas-13) [reply src/js/helpers.js:207]: I don't think this actually works here as for different classes(the school kind) it seems to be inconsistent whether that CSS is present. So in some cases, a class may not have the missing indicator and in other cases, they'll have it hidden and in other cases, they'll have it and it'll be unhidden.

Comment (Suhas-13) [reply src/js/helpers.js:207]: I don't think this actually works here as for some classes this will be null due to inconsistent CSS(some classes don't contain the missingicon gif and some do), and as such it should be counted as not missing if it doesn't exist.

File: src/js/helpers.js (hunk 1 above)
Comment (Suhas-13) [reply src/js/helpers.js]: fixed.

**Review by ARtheboss — APPROVED** [review]
